import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LargeCard from "../components/LargeCard";
import MediumCard from "../components/MediumCard";
import SmallCard from "../components/SmallCard";

export default function Home({ exploreData, cardsData }) {
  console.log(cardsData);
  return (
    <div>
      <Head>
        <title>Love's Airbnb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main>
        <Header />
        <Banner />
        <main className="max-w-7xl mx-auto px-8 sm:px-16">
          <section className="pt-6">
            <h2 className="lg:text-2xl text-xl font-bold">Explore Nearby</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4">
              {exploreData?.map((item, index) => (
                <SmallCard
                  key={index}
                  image={item.img}
                  location={item.location}
                  distance={item.distance}
                />
              ))}
            </div>
          </section>
          <section className="pt-20">
            <h2 className="text-xl lg:text-2xl font-bold">Live Anywhere</h2>
            <div className="flex space-x-3 p-3 overflow-scroll scrollbar-hide">
              {cardsData.map((card, index) => (
                <MediumCard key={index} image={card.img} title={card.title} />
              ))}
            </div>
          </section>
          <LargeCard
            image="https://links.papareact.com/4cj"
            title="The Greatest Outdoors"
            description="Wishlists curated by Airbnb"
            buttonText="Get Inspired"
          />
        </main>
        <Footer />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://links.papareact.com/pyp");
  const exploreData = await res.json();

  const response = await fetch("https://links.papareact.com/zp1");

  const cardsData = await response.json();

  return {
    props: {
      exploreData,
      cardsData,
    },
  };
}
